# fly.toml app configuration file generated for walk-my-dog-delicate-field-8744 on 2023-11-17T10:21:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "walk-my-dog-delicate-field-8744"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
